### ISSUE TITLE
feature: Update Open Graph Social Card Designs

### ISSUE THREAD

**Issue by getaheaddev** [open-sauced/opengraph#44]
There have been updates to the social card design

<img width="1200" alt="socialDashCard-linkedin-dashboard-card" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/122071536/34279b25-fb10-41cf-b582-aa3dc65602b4">

[[Project Dashboard](https://www.figma.com/file/jymWgr4kOgSpZYEoFrlgZQ/Design-System?type=design&node-id=1277-2474&t=BSQ0EN4E1Wtyb6Fx-4)]

<img width="1192" alt="socialUserCard-linkedin-user-profile-card" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/122071536/1d943bec-d0e7-4e68-9460-089c8839fda1">

[[User Profile Card](https://www.figma.com/file/jymWgr4kOgSpZYEoFrlgZQ/Design-System?type=design&node-id=1277-2365&t=BSQ0EN4E1Wtyb6Fx-4)]

<img width="1192" alt="socialUserCard-linkedin-highlight" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/122071536/d297f85b-7437-4e95-97e1-892180785d08">

[[Highlights](https://www.figma.com/file/jymWgr4kOgSpZYEoFrlgZQ/Design-System?type=design&node-id=1278-2505&t=BSQ0EN4E1Wtyb6Fx-4)]

**Comment by davidgetahead** [comment]
> There have been updates to the social card design
> 
> <img alt="socialDashCard-linkedin-dashboard-card" width="1200" src="https://user-images.githubusercontent.com/122071536/237416898-34279b25-fb10-41cf-b582-aa3dc65602b4.png">
> [[Project Dashboard](https://www.figma.com/file/jymWgr4kOgSpZYEoFrlgZQ/Design-System?type=design&node-id=1277-2474&t=BSQ0EN4E1Wtyb6Fx-4)]
> 
> <img alt="socialUserCard-linkedin-user-profile-card" width="1192" src="https://user-images.githubusercontent.com/122071536/237411391-1d943bec-d0e7-4e68-9460-089c8839fda1.png">
> [[User Profile Card](https://www.figma.com/file/jymWgr4kOgSpZYEoFrlgZQ/Design-System?type=design&node-id=1277-2365&t=BSQ0EN4E1Wtyb6Fx-4)]
> 
> <img alt="socialUserCard-linkedin-highlight" width="1192" src="https://user-images.githubusercontent.com/122071536/237416958-d297f85b-7437-4e95-97e1-892180785d08.png">
> [[Highlights](https://www.figma.com/file/jymWgr4kOgSpZYEoFrlgZQ/Design-System?type=design&node-id=1278-2505&t=BSQ0EN4E1Wtyb6Fx-4)]

For some reason these aren't showing so I'm replacing them below

<img width="1200" alt="socialDashCard-linkedin-dashboard-card_A" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/49037614/d455f65d-bce6-40d7-a96c-4d7e6dd3f41c">

<img width="1192" alt="socialUserCard-linkedin-user-profile-card_B" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/49037614/806d2414-0d00-4537-94d0-040aa61435f0">

<img width="1192" alt="socialUserCard-linkedin-highlight_C" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/49037614/ad06b14f-6881-4d49-b10d-d41530eb74ca">

**Comment by OgDev-01** [comment]
So we are no longer displaying the highlight body... that fair :<
