### ISSUE TITLE
docs: project readme needs updating  

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/opengraph#48]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior
The current readme does not include some steps needed to enable new contributors generate test social cards locally..

### Suggested solution
Update current readme to include missing steps 

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
.take
