### ISSUE TITLE
Feature: Add node emoji to highlight cards

### ISSUE THREAD

**Issue by bdougie** [open-sauced/opengraph#50]
### Type of feature

🍕 Feature

### Current behavior

Emojis are not being generated in the card preview. 

https://insights.opensauced.pizza/feed/171

![Screen Shot 2023-06-06 at 10 59 06 AM](https://github.com/open-sauced/opengraph.opensauced.pizza/assets/5713670/23aa86cb-c02b-4a1e-a2a9-5fd04ac26924)

### Suggested solution

Use node-emoji wrapper for copy. We use it in open-sauced/hot

https://github.com/open-sauced/hot/pulls?q=is%3Apr+emoji+is%3Aclosed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Clicking on the link in the issue gave me this issue: 

![image](https://github.com/open-sauced/opengraph/assets/18273833/a5cf7be1-201d-4716-abea-64953d5b2b95)

```
Runtime.UnhandledPromiseRejection: TypeError: fetch failed
    at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```
```
Runtime.UnhandledPromiseRejection - TypeError: fetch failed
```
```
Netlify internal ID: 01H5YKK2BXRAP2QXDVZ283Y20B
```

Refreshing the page solved the issue.

**Comment by a0m0rajab** [comment]
This is the result I got when I paste the link on FaceBook 
![image](https://github.com/open-sauced/opengraph/assets/18273833/000a4190-5325-4d8e-b8b5-f7c4688145be)

**Comment by a0m0rajab** [comment]
This is the related component in this repo: 

https://github.com/open-sauced/opengraph/blob/bf8992e7b7b5764ff017ed90548cbc6bf4b58aa0/src/social-card/templates/highlight-card.template.ts#L21

This is an example of fixing it based on the suggestion in the issue: 
https://github.com/open-sauced/hot/pull/449/files

**Comment by a0m0rajab** [comment]
I worked on this and used `node-emoji` but it seems not to work, not sure if it's only on my PC, here is the code: 
https://github.com/a0m0rajab/opengraph/tree/feat-add-emoji

But one of the things that I got curious about is the HTML/image convertor: the solution might be there: 
https://github.com/vercel/satori#dynamically-load-emojis-and-fonts

I will do further testing later.

**Comment by a0m0rajab** [comment]
Satory/Vercel is using an API/CDN to get the SVG of the emoji: 
https://github.com/vercel/satori/blob/2e8dcb486f3dadeb6fc2e8790cb822a72893a21a/playground/pages/index.tsx#L102

We might need to implement something similar: 

https://github.com/vercel/satori/blob/2e8dcb486f3dadeb6fc2e8790cb822a72893a21a/playground/utils/twemoji.ts

I will stop here now and check it at another time.

**Comment by bdougie** [comment]
> Clicking on the link in the issue gave me this issue:
> 
> ![image](https://user-images.githubusercontent.com/18273833/255325559-a5cf7be1-201d-4716-abea-64953d5b2b95.png)
> 
> ```
> Runtime.UnhandledPromiseRejection: TypeError: fetch failed
>     at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)
>     at process.emit (node:events:525:35)
>     at process.emit (node:domain:489:12)
>     at emit (node:internal/process/promises:140:20)
>     at processPromiseRejections (node:internal/process/promises:274:27)
>     at processTicksAndRejections (node:internal/process/task_queues:97:32)
> ```
> 
> ```
> Runtime.UnhandledPromiseRejection - TypeError: fetch failed
> ```
> 
> ```
> Netlify internal ID: 01H5YKK2BXRAP2QXDVZ283Y20B
> ```
> 
> Refreshing the page solved the issue.

This is do to the image generation failing because the data is not ready, I believe. Refreshing hits the cache. We will honestly need to look into using an edge function for all of this in the future. 

That work is being explored here. https://github.com/open-sauced/insights/pull/1400

I will look at this deeper on Monday. Interesting that nore-emoji did not work in this case.

**Comment by a0m0rajab** [comment]
Thank you for that! Looking forward to read your review.

**Comment by a0m0rajab** [comment]
Shower thoughts: This issue could be a great case study for why you need to provide a suggestion to your issue. 
The suggestion that you @bdougie provided saved a couple of hours (between 2-3 hours) of trial and error and debugging, since the `node-emoji` worked on other project it proved to me that the issue is not in the HTML/React part of the code! Otherwise, it would be hard to get out of the rabbit hole.

**Comment by bdougie** [comment]
Indeed. I need to get in more issues and make proper suggestions.

Hoping we can start coordinating more triaging with the team.

**Comment by a0m0rajab** [comment]
I would like to help in case if I can do anything there, when the PR get accepted I am thinking to write a blog about this. Focusing on the value of providing suggested solutions.
